version: '3.8'  # Specifies the version of Docker Compose.

services:
  damage-api:
    build: .
    container_name: damage-api-container  # Name of the container
    ports:
      - "5000:5000"  # Maps port 5000 inside the container to port 5000 on the host
    volumes:
      - .:/app  # Mounts the current directory to /app inside the container

networks:
  flask-network:
    driver: bridge  # Use bridge network mode (default)
